### ISSUE TITLE
License of the project?

### ISSUE THREAD

**Issue by marynate** [JSandusky/UrhoAngelscriptIDE#1]
Very usefull tool! But noticed that there's no license terms mentioned in the readme, is it MIT? It might be a good idea to include a license. md file in the repo to make it clear. Just a suggestion.

**Comment by JSandusky** [comment]
The intended license is to be MIT. However I'm going through and reviewing everything to make sure there isn't anything that interferes with that (ie- the images are from the Fugue Icon library, which is CC and doesn't intefere).

**Comment by marynate** [comment]
Cool, thanks!
