### ISSUE TITLE
Spaces in path

### ISSUE THREAD

**Issue by hdunderscore** [JSandusky/UrhoAngelscriptIDE#4]
I think there are some issues with spaces in the project path, eg: Compiling and running both seem to trip up in these cases.

**Comment by JSandusky** [comment]
Path strings containing spaces needed to be quoted when building arguments string to start external processes. I still need to check it out to be sure, but regardless quoting them is proper practice.

**Comment by hdunderscore** [comment]
I pulled the new change and that helps. One more thing though, to avoid an issue with #include paths, I had to set the working directory: 

`pi.StartInfo.WorkingDirectory = IDEProject.inst().Settings.ProjectPath;` in `IDEView.xaml.cs`.

Perhaps I did something wrong?

**Comment by JSandusky** [comment]
That should be correct. I clearly broke it at some point.

**Comment by hdunderscore** [comment]
Latest commit resolves all issues: https://github.com/JSandusky/UrhoAngelscriptIDE/commit/a6675accf79ceed93e70b77fe611cf5117f82fc6
